apiVersion: v1
kind: Service
metadata:
  name: backend-svc

spec:
  type: ClusterIP    # change to nodeport if not using ingress
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
    # nodePort: 30080